### ISSUE TITLE
GDSC.analyse mobem dependent error - 'DataFrame' object has no attribute 'DRUG_ID'

### ISSUE THREAD

**Issue by howard-lightfoot** [CancerRxGene/gdsctools#156]
I get the following error with a particular mobem but not with others. The Drug decode and IC50 matrix have not changed. No output is produced for the KIRC analysis.

I will send the example files separately.

![screen shot 2016-10-31 at 09 56 11](https://cloud.githubusercontent.com/assets/15104489/19850444/716907dc-9f50-11e6-99b8-148124448d9f.png)

**Comment by cokelaer** [comment]
I have identify the issue. This is a special case where there is no tests to be done (not enough features). The empty dataframe returned is not handled properly. I have fixed this issue locally and this will be fixed in the next release.

**Comment by cokelaer** [comment]
Should work with version 0.15.0
